### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [highbyte/dotnet-6502#18]
It has been noticed that while using highbyte/sonarscan-dotnet@2.0 your sonarProjectKey highbyte_dotnet-6502 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by highbyte** [comment]
Thanks for taking time to file a potential secret leak.

Though the Sonar Project Key is not a secret or a credential, it's not a sensitive information that needs to be protected. It's part of the public URL in SonarCloud: https://sonarcloud.io/dashboard?id=highbyte_dotnet-6502

The sensitive credential is the Sonar _Token_ which is stored in a GitHub secret. You can see it referenced in the workflow file like this: SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
